from .libro import Libro as LibroResources
from .libro import Libros as LibrosResources
from .prestamo import Prestamo as PrestamoResources
from .prestamo import Prestamos as PrestamosResources
from .usuario import Usuario as UsuarioResources
from .usuario import Usuarios as UsuariosResources
from .valoracion import Valoracion as ValoracionResources
from .notificaciones import Notificacion as NotificacionResources
from .login import Login as LoginResources
from .signin import Signin as SigninResources
from .configuracion import Configuracion as ConfiguracionResources
from .comentarios import Comentario as ComentarioReources
from .valoracion import Valoraciones as ValoracionesResources
from .comentarios import Comentarios as ComentariosResources